import Vue from 'vue'
import Vuex from 'vuex'

Vue.use(Vuex)

export default new Vuex.Store({
  state: {
    Words: [
      { section: 'Shapes', words: [
        { eng: 'equilateral triangle', ukr: 'рівносторонній трикутник' },
        { eng: 'isosceles triangle', ukr: 'рівнобедрений трикутник' },
        { eng: 'sphere', ukr: 'куля' },
        { eng: 'pentagon', ukr: '5-кутник' },
        { eng: 'hexagon', ukr: '6-кутник' },
        { eng: 'octagon', ukr: '8-кутник' },
        { eng: 'coffin', ukr: 'труна' },
        { eng: 'kite', ukr: 'паперовий змій' },
        { eng: 'petal', ukr: 'пелюстка' },
        { eng: 'shell', ukr: 'черепашка' }
      ] },
      { section: 'Weather', words: [
        { eng: 'scorching', ukr: 'пекучий, спекотний' },
        { eng: 'sultry', ukr: 'задушливий' },
        { eng: 'chilly', ukr: 'прохолодний, вологий' },
        { eng: 'frosty', ukr: 'морозний' },
        { eng: 'sunshine', ukr: 'сонячне світло' },
        { eng: 'glitter', ukr: 'виблискувати, блищати' },
        { eng: 'peep', ukr: 'підглядати, з\'являтися' },
        { eng: 'a ray of sunlight', ukr: 'промінь сонця' },
        { eng: 'damp', ukr: 'вологий' },
        { eng: 'moist', ukr: 'вогкий' },
        { eng: 'moisture', ukr: 'вогкість' },
        { eng: 'humidity', ukr: 'вологість' },
        { eng: 'drizzle', ukr: 'мряка, дрібний дощ' },
        { eng: 'thunderstorm', ukr: 'гроза' },
        { eng: 'downpour', ukr: 'злива' },
        { eng: 'hail', ukr: 'град' },
        { eng: 'hailstone', ukr: 'градина' },
        { eng: 'puddle', ukr: 'калюжа' },
        { eng: 'mud', ukr: 'бруд, болото' },
        { eng: 'gale', ukr: 'сильний вітер' },
        { eng: 'a clap of thunder', ukr: 'удар грому' },
        { eng: 'a gust of wind', ukr: 'порив вітру' },
        { eng: 'snowstorm', ukr: 'сніжна буря' },
        { eng: 'blizzard', ukr: 'заметіль' },
        { eng: 'slippery', ukr: 'слизький' },
        { eng: 'icy', ukr: 'крижаний, слизький' },
        { eng: 'mist', ukr: 'легкий туман, імла' },
        { eng: 'flower', ukr: 'цвісти' },
        { eng: 'bloom', ukr: 'цвісти, розцвітати' },
        { eng: 'flourish', ukr: 'пишно рости, процвітати' }
      ] },
      { section: 'People In Your Life', words: [
        { eng: 'acquaintance', ukr: 'знайомство' },
        { eng: 'bachelor', ukr: 'холостяк' },
        { eng: 'best man', ukr: 'друг нареченого' },
        { eng: 'bridesmaid', ukr: 'подружка нареченої' },
        { eng: 'daughter-in-law', ukr: 'невістка' },
        { eng: 'father-in-law', ukr: 'свекор, тесть' },
        { eng: 'fiance / groom', ukr: 'наречений' },
        { eng: 'fiancee / bride', ukr: 'наречена' },
        { eng: 'foster', ukr: 'виховувати (чужу дитину)' },
        { eng: 'foster parents', ukr: 'прийомні батьки' },
        { eng: 'grandchildren', ukr: 'внуки' },
        { eng: 'granny', ukr: 'бабуся' },
        { eng: 'in-laws', ukr: 'близькі родичі чоловіка або дружини' },
        { eng: 'mother-in-law', ukr: 'свекруха, теща' },
        { eng: 'nephew', ukr: 'племінник' },
        { eng: 'niece', ukr: 'племінниця' },
        { eng: 'nuclear family', ukr: 'мала родина' },
        { eng: 'sibling', ukr: 'рідний брат або сестра' },
        { eng: 'son-in-law', ukr: 'зять' },
        { eng: 'spinster', ukr: 'стара діва' },
        { eng: 'spouse', ukr: 'чоловік, дружина' },
        { eng: 'stepdaughter', ukr: 'пасербиця' },
        { eng: 'stepfather', ukr: 'вітчим' },
        { eng: 'stepmother', ukr: 'мачуха' },
        { eng: 'stepson', ukr: 'пасинок' },
        { eng: 'triplets', ukr: 'трійня' },
        { eng: 'twins', ukr: 'близнюки' }
      ] },
      { section: 'Relations & Family History, Life', words: [
        { eng: 'be a role model', ukr: 'бути зразком для наслідування' },
        { eng: 'fall out (with sb)', ukr: 'сваритися' },
        { eng: 'generation gap', ukr: 'непорозуміння поколінь' },
        { eng: 'get on well (with sb)', ukr: 'добре ладнати з кимось' },
        { eng: 'have an argument / a disagreement / a row (with sb)', ukr: 'посваритися' },
        { eng: 'make up (with sb)', ukr: 'помиритися' },
        { eng: 'relation (close / distant)', ukr: 'родич (близький / далекий)' },
        { eng: 'ancestor', ukr: 'предок, прабатько' },
        { eng: 'descendant', ukr: 'нащадок' },
        { eng: 'forebear', ukr: 'предок, попередник' },
        { eng: 'genealogy', ukr: 'родовід' },
        { eng: 'origin', ukr: 'походження' },
        { eng: 'trace back', ukr: 'відслідкувати' },
        { eng: 'adolescence', ukr: 'юність' },
        { eng: 'adolescent', ukr: 'підліток, юнак, підлітковий' },
        { eng: 'adulthood', ukr: 'повноліття, зрілість' },
        { eng: 'elderly', ukr: 'похилого віку' },
        { eng: 'toddler', ukr: 'дитина, яка вчиться ходити' },
        { eng: 'youth', ukr: 'молодь, юність' },
        { eng: 'grown-up', ukr: 'дорослий' }
      ] },
      { section: 'Describing Personality', words: [
        { eng: 'adventurous', ukr: 'який людить пригоди' },
        { eng: 'ambition', ukr: 'прагнення, мета' },
        { eng: 'ambitious', ukr: 'амбітний' },
        { eng: 'amusing', ukr: 'смішний' },
        { eng: 'arrogant', ukr: 'зарозумілий, пихатий' },
        { eng: 'bad tempered', ukr: 'злий, дратівливий' },
        { eng: 'boastful', ukr: 'хвалькуватий' },
        { eng: 'bossy', ukr: 'який розпоряджається, заправляє усім' },
        { eng: 'bright', ukr: 'здібний, кмітливий, тямущий' },
        { eng: 'broad-minded', ukr: 'з широким кругозором' },
        { eng: 'candid', ukr: 'прямий, щирий' },
        { eng: 'carefree', ukr: 'безтурботний' },
        { eng: 'careless', ukr: 'легковажний' },
        { eng: 'characteristics', ukr: 'характерні риси, особливості' },
        { eng: 'charming', ukr: 'чарівний, милий' },
        { eng: 'chatterbox', ukr: 'базіка' },
        { eng: 'chatty / talkative', ukr: 'балакучий' },
        { eng: 'cheerful', ukr: 'бадьорий' },
        { eng: 'conceited', ukr: 'самовдоволений' },
        { eng: 'cruel', ukr: 'жорстокий, безжалісний' },
        { eng: 'dependable', ukr: 'надійний' },
        { eng: 'determined', ukr: 'рішучий' },
        { eng: 'dull', ukr: 'тупий, безглуздий' },
        { eng: 'easy-going', ukr: 'добродушно-веселий' },
        { eng: 'frank', ukr: 'відвертий' },
        { eng: 'good-natured', ukr: 'добродушний' },
        { eng: 'gullible', ukr: 'легковірний' },
        { eng: 'hypocritical', ukr: 'лицемірний' },
        { eng: 'idle', ukr: 'байдикуючий' },
        { eng: 'ill-mannered', ukr: 'невихований' },
        { eng: 'immature', ukr: 'незрілий' },
        { eng: 'impartial', ukr: 'неупереджений' },
        { eng: 'insecure', ukr: 'ненадійний, небезпечний' },
        { eng: 'irritable', ukr: 'дратівливий' },
        { eng: 'judgemental', ukr: 'розсудливий' },
        { eng: 'just', ukr: 'справедливий' },
        { eng: 'lively', ukr: 'жвавий' },
        { eng: 'mature', ukr: 'зрілий' },
        { eng: 'mean', ukr: 'скупий, убогий, підлий, підступний' },
        { eng: 'messy', ukr: 'брудний' },
        { eng: 'modest', ukr: 'скромний' },
        { eng: 'narrow-minded', ukr: 'обмежений, недалекий' },
        { eng: 'nasty', ukr: 'огидний, мерзенний' },
        { eng: 'neat', ukr: 'чистий, охайний' },
        { eng: 'obedient', ukr: 'слухняний' },
        { eng: 'outgoing', ukr: 'чуйний, товариський' },
        { eng: 'reasonable', ukr: 'розумний' },
        { eng: 'rebellious', ukr: 'бунтарський' },
        { eng: 'ruthless', ukr: 'безжалісний' },
        { eng: 'self-assured', ukr: 'самовпевнений' },
        { eng: 'self-centered', ukr: 'зосереджений на собі' },
        { eng: 'self-conscious', ukr: 'соромливий' },
        { eng: 'selfless', ukr: 'самовідданий' },
        { eng: 'short-tempered', ukr: 'запальний, нестримний' },
        { eng: 'strict', ukr: 'строгий' },
        { eng: 'strong-willed', ukr: 'рішучий, вольовий' },
        { eng: 'stubborn', ukr: 'впертий' },
        { eng: 'sweet', ukr: 'милий, привітливий' },
        { eng: 'sympathetic', ukr: 'співчутливий' },
        { eng: 'tidy', ukr: 'акуратний' },
        { eng: 'trait', ukr: 'характерна риса' },
        { eng: 'trustworthy', ukr: 'той, що заслуговує довіри' },
        { eng: 'two-faced', ukr: 'дволикий' },
        { eng: 'unreasonable', ukr: 'нерозсудливий' },
        { eng: 'unscrupulous', ukr: 'недобросовісний' },
        { eng: 'unselfish', ukr: 'безкорисливий' },
        { eng: 'vain', ukr: 'самовдоволений, самозакоханий' }
      ] },
      { section: 'Feelings And Emotions', words: [
        { eng: 'adore', ukr: 'обожнювати' },
        { eng: 'amazed', ukr: 'здивований, вражений' },
        { eng: 'anxious', ukr: 'стурбований, схвильований' },
        { eng: 'astonished', ukr: 'здивований' },
        { eng: 'bewildered', ukr: 'збентежений' },
        { eng: 'delighted', ukr: 'захоплений' },
        { eng: 'detest', ukr: 'ненавидіти' },
        { eng: 'excited', ukr: 'збуджений, схвильований' },
        { eng: 'exhausted', ukr: 'виснажений' },
        { eng: 'fed up (with sth)', ukr: 'ситий' },
        { eng: 'gloomy', ukr: 'похмурий' },
        { eng: 'hostile', ukr: 'ворожий' },
        { eng: 'idolise', ukr: 'боготворити' },
        { eng: 'insensitive', ukr: 'нечутливий, байдужий' },
        { eng: 'intimidating', ukr: 'те, що лякає, нервує' },
        { eng: 'loathe', ukr: 'відчувати відразу' },
        { eng: 'lose one\'s temper', ukr: 'виходити з себе' },
        { eng: 'melancholic', ukr: 'меланхолійний' },
        { eng: 'mesmerize', ukr: 'зачаровувати, гіпнотизувати' },
        { eng: 'mind one\'s own business', ukr: 'не втручатися у чужі справи' },
        { eng: 'miserable', ukr: 'нещасний, жалюгідний' },
        { eng: 'moody', ukr: 'який легко піддається змінам настрою' },
        { eng: 'moved', ukr: 'заклопотаний' },
        { eng: 'on top of the world', ukr: 'бути щасливим, у гарному настрою' },
        { eng: 'over the moon', ukr: 'надзвичайно щасливий' },
        { eng: 'overwhelmed', ukr: 'переповнений, приголомшений' },
        { eng: 'reluctant', ukr: 'неохочий' },
        { eng: 'restless', ukr: 'неспокійний' },
        { eng: 'terrified (of sth)', ukr: 'жахатися чогось' },
        { eng: 'thrilled (with sth)', ukr: 'бути у захваті від чогось' },
        { eng: 'touched', ukr: 'зворушений' },
        { eng: 'weary', ukr: 'стомлений' }
      ] },
      { section: 'People and Society', words: [
        { eng: 'associate / companion', ukr: 'товариш, компаньйон' },
        { eng: 'co-worker / workmate', ukr: 'товариш по роботі' },
        { eng: 'pal', ukr: 'приятель' },
        { eng: 'buddy', ukr: 'дружище' },
        { eng: 'get together with', ukr: 'збиратися, зустрічатися' },
        { eng: 'get on with', ukr: 'ладити' },
        { eng: 'have much in common', ukr: 'мати багато спільного' },
        { eng: 'keypal / penfriend', ukr: 'друг по листуванню' },
        { eng: 'keep in touch', ukr: 'підтримувати стосунки' },
        { eng: 'row', ukr: 'сварка' },
        { eng: 'roommate', ukr: 'товариш по кімнаті' },
        { eng: 'similar background', ukr: 'однакове походження' }
      ] },
      { section: 'Mass Media', words: [
        { eng: 'ad / advert / advertisement', ukr: 'оголошення, реклама' },
        { eng: 'amateur', ukr: 'любитель, аматор' },
        { eng: 'broadcast', ukr: 'транслювати' },
        { eng: 'cable TV', ukr: 'кабельне телебачення' },
        { eng: 'circulation', ukr: 'тиражі' },
        { eng: 'coach potato', ukr: 'домосід' },
        { eng: 'column', ukr: 'колонка, рубрика' },
        { eng: 'comic strip', ukr: 'комікс' },
        { eng: 'daily paper', ukr: 'газета, яка виходить щоденно' },
        { eng: 'edition', ukr: 'видання' },
        { eng: 'glossy', ukr: 'глянцевий, блискучий' },
        { eng: 'issue', ukr: 'випуск' },
        { eng: 'live broadcast', ukr: 'транслювати наживо' },
        { eng: 'remote', ukr: 'віддалений' },
        { eng: 'satellite TV', ukr: 'супутникове телебачення' },
        { eng: 'soap opera', ukr: 'телесеріал' },
        { eng: 'talk show host', ukr: 'ведучий ток-шоу' }
      ] },
      { section: 'Music', words: [
        { eng: 'beat', ukr: 'такт' },
        { eng: 'chord', ukr: 'акорд' },
        { eng: 'conduct', ukr: 'диригувати' },
        { eng: 'orchestra', ukr: 'оркестр' },
        { eng: 'rhythm', ukr: 'ритм' },
        { eng: 'release', ukr: 'випускати (альбом)' },
        { eng: 'outdoors', ukr: 'на свіжому повітрі' },
        { eng: 'to pass time', ukr: 'проводити час' }
      ] },
      { section: 'Free Time', words: [
        { eng: 'spare time', ukr: 'вільний час' },
        { eng: 'backgammon', ukr: 'нарди' },
        { eng: 'hearts', ukr: 'чирви' },
        { eng: 'clubs', ukr: 'трефи' },
        { eng: 'diamonds', ukr: 'бубни' },
        { eng: 'spades', ukr: 'піки' },
        { eng: 'ace', ukr: 'туз' },
        { eng: 'jack', ukr: 'валет' },
        { eng: 'rook', ukr: 'тура' },
        { eng: 'queen', ukr: 'ферзь, королева, дама' },
        { eng: 'bishop', ukr: 'слон' },
        { eng: 'pawn', ukr: 'пішак' },
        { eng: 'choir', ukr: 'хор' },
        { eng: 'dice', ukr: 'гральні кості' },
        { eng: 'dominoes', ukr: 'доміно' },
        { eng: 'draughts / checkers', ukr: 'шашки' },
        { eng: 'leisure', ukr: 'дозвілля' },
        { eng: 'recreation', ukr: 'відпочинок, розвага' }
      ] },
      { section: 'Activities', words: [
        { eng: 'bungee jumping', ukr: 'стрибки з канатом' },
        { eng: 'gardening', ukr: 'садівництво' },
        { eng: 'hillwalking', ukr: 'походи у гори' },
        { eng: 'rollerblading', ukr: 'катання на роликах' },
        { eng: 'scuba diving', ukr: 'пірнання з аквалангом' },
        { eng: 'water-skiing', ukr: 'водні лижі' },
        { eng: 'jigsaw', ukr: 'пазл, головоломка' },
        { eng: 'pastry', ukr: 'борошняні вироби' },
        { eng: 'pattern', ukr: 'узор, візерунок' },
        { eng: 'sewing machine', ukr: 'швейна машинка' },
        { eng: 'stamp', ukr: 'марка' },
        { eng: 'go for a drive in the country', ukr: 'покататися у сільській місцевості' },
        { eng: 'go for a swim', ukr: 'поплавати' },
        { eng: 'go clubbing', ukr: 'ходити у клуби' },
        { eng: 'go fishing', ukr: 'рибалити' },
        { eng: 'go to the pub', ukr: 'ходити у бар' },
        { eng: 'meet up with', ukr: 'зустрічатися з' }
      ] },
      { section: 'Type Of Housing', words: [
        { eng: 'bed sitter', ukr: 'житлова кімната' },
        { eng: 'block of flats / apartment', ukr: 'багатоквартирний будинок' },
        { eng: 'bungalow', ukr: '1-поверхова дача з верандою' },
        { eng: 'detached house', ukr: 'окремий будинок' },
        { eng: 'penthouse', ukr: 'фенешабельна квартира в надбудові на даху будинку' },
        { eng: 'semi-detached house', ukr: 'будинок на 1 родину, що має спільну стіну з сусіднім будинком.' },
        { eng: 'skyscraper', ukr: 'хмарочос' },
        { eng: 'terraced house', ukr: 'ряд стандартних будинків уздовж вулиці' },
        { eng: 'tower block', ukr: 'дім-вежа' }
      ] },
      { section: 'Size And Condition', words: [
        { eng: 'cramped', ukr: 'тісний' },
        { eng: 'furnished', ukr: 'умебльований' },
        { eng: 'spacious / roomy', ukr: 'великий, прострий' },
        { eng: 'fully equipped', ukr: 'повністю обладнаний' },
        { eng: 'run-down', ukr: 'занедбаний' },
        { eng: 'tiny', ukr: 'дуже маленький' },
        { eng: 'unfurnished', ukr: 'немебльований' }
      ] },
      { section: 'Location', words: [
        { eng: 'country / rural', ukr: 'сільський' },
        { eng: 'county', ukr: 'округ' },
        { eng: 'district', ukr: 'район' },
        { eng: 'farmland', ukr: 'сільськогосподарський район' },
        { eng: 'hamlet', ukr: 'селище' },
        { eng: 'home town', ukr: 'рідне місто' },
        { eng: 'inhabitant', ukr: 'житель, мешканець' },
        { eng: 'outskirts', ukr: 'околиці' },
        { eng: 'resort', ukr: 'курорт' },
        { eng: 'slums', ukr: 'нетрі' },
        { eng: 'suburb', ukr: 'передмістя' }
      ] },
      { section: 'In The House', words: [
        { eng: 'attic / loft', ukr: 'горище' },
        { eng: 'basement', ukr: 'фундамент' },
        { eng: 'cellar', ukr: 'підвал' },
        { eng: 'chimney', ukr: 'димохід' },
        { eng: 'downstairs', ukr: 'нижня частина будинку' },
        { eng: 'drain pipe', ukr: 'стічна труба' },
        { eng: 'flowerbed', ukr: 'клумба' },
        { eng: 'lawn', ukr: 'газон' },
        { eng: 'patio', ukr: 'внутрішній дворик' },
        { eng: 'porch', ukr: 'ганок' },
        { eng: 'shrubbery', ukr: 'алея, обсаджена кущами' },
        { eng: 'sprinkler system', ukr: 'поливна система' },
        { eng: 'staircase', ukr: 'сходи' },
        { eng: 'upstairs', ukr: 'верхній поверх' },
        { eng: '(front / back) yard', ukr: 'передній / задній дворик' },
        { eng: 'blind', ukr: 'штора, жалюзі' },
        { eng: 'ceiling', ukr: 'стеля' },
        { eng: 'curtain', ukr: 'завіса' },
        { eng: 'light bulb', ukr: 'лампочка' },
        { eng: 'net curtain', ukr: 'тюль' },
        { eng: 'window sill', ukr: 'підвіконня' },
        { eng: 'plughole', ukr: 'штепсельне гніздо' },
        { eng: 'razor', ukr: 'бритва' },
        { eng: 'tap', ukr: 'кран' },
        { eng: 'tiles', ukr: 'плитка' },
        { eng: 'towel rail', ukr: 'сушка для рушників' },
        { eng: 'washbasin', ukr: 'умивальна раковина' },
        { eng: 'blanket', ukr: 'ковдра' },
        { eng: 'bookshelf', ukr: 'книжкова полиця' },
        { eng: 'chest of drawers', ukr: 'комод' },
        { eng: 'dressing table', ukr: 'туалетний столик' },
        { eng: 'duvet', ukr: 'пухова ковдра' },
        { eng: 'pillow', ukr: 'подушка' },
        { eng: 'rug', ukr: 'килимок' },
        { eng: 'sheet', ukr: 'простирадло' },
        { eng: 'VCR (video cassette recorder)', ukr: 'відеомагнітофон' },
        { eng: 'cooker', ukr: 'плита' },
        { eng: 'cupboard', ukr: 'буфет' },
        { eng: 'draining board', ukr: 'сушка' },
        { eng: 'freezer', ukr: 'морозильна камера' },
        { eng: 'fridge / refrigerator', ukr: 'холодильник' },
        { eng: 'oven', ukr: 'піч, духовка' },
        { eng: 'running water', ukr: 'вода з крана' },
        { eng: 'sink', ukr: 'раковина' },
        { eng: 'hall', ukr: 'прихожа' },
        { eng: 'back door', ukr: 'чорний хід' },
        { eng: 'doorbell', ukr: 'дверний дзвінок' },
        { eng: 'doormat', ukr: 'килимок для витирання' },
        { eng: 'front door', ukr: 'парадний вхід' }
      ] },
      { section: 'Looking After Your House', words: [
        { eng: 'broom', ukr: 'мітла' },
        { eng: 'do up', ukr: 'прибирати' },
        { eng: 'dustpan', ukr: 'лопатка для сміття' },
        { eng: 'leak', ukr: 'протікати' },
        { eng: 'maintenance', ukr: 'експлуатація, обслуговування' },
        { eng: 'mend', ukr: 'ремонтувати' },
        { eng: 'mop (the floor)', ukr: 'мити підлогу' },
        { eng: 'vacuum cleaner', ukr: 'пилосос' }
      ] },
      { section: 'Leaving And Returning To Your House', words: [
        { eng: 'commute (to work, school)', ukr: 'добиратися (на роботу, до школи)' },
        { eng: 'feel homesick', ukr: 'сумувати за домом' },
        { eng: 'lock', ukr: 'замикати' },
        { eng: 'move house', ukr: 'переїжджати' },
        { eng: 'move in', ukr: 'заселитися' },
        { eng: 'move out', ukr: 'виселетися (з квартири)' },
        { eng: 'stay in', ukr: 'залишатися вдома' }
      ] },
      { section: 'Renting And Buying / Selling A Home', words: [
        { eng: 'accommodation', ukr: 'зручність, житло' },
        { eng: 'bill (electricity / utility)', ukr: 'рахунок (за світло, комунальні послуги)' },
        { eng: 'estate agent', ukr: 'агент з продажу нерухомості' },
        { eng: 'flatmate', ukr: 'людина, з якою живеш у кімнаті' },
        { eng: 'inclusive', ukr: 'який включає' },
        { eng: 'landlady', ukr: 'домовласниця' },
        { eng: 'landlord', ukr: 'власник квартири' },
        { eng: 'let (a flat / house)', ukr: 'здавати (квартиру, будинок)' },
        { eng: 'lodger', ukr: 'квартирант' },
        { eng: 'lodgings', ukr: 'тимчасове житло' },
        { eng: 'pay the rent', ukr: 'платити квартирну плату' },
        { eng: 'property', ukr: 'власність, майно' },
        { eng: 'rent', ukr: 'квартирна або орендна плата' },
        { eng: 'tenant', ukr: 'наймач, орендар' },
        { eng: 'neighbourhood', ukr: 'сусідство, район' }
      ] },
      { section: 'Daily Routine', words: [
        { eng: 'babysit', ukr: 'приглядати за дитиною' },
        { eng: 'brush (one\'s) teeth', ukr: 'чистити зуби' },
        { eng: 'domestic / household chores', ukr: 'хатні справи' },
        { eng: 'clear up', ukr: 'упорядкувати' },
        { eng: 'do the cooking', ukr: 'готувати їсти' },
        { eng: 'do the dusting', ukr: 'витирати пилюку' },
        { eng: 'do the ironing', ukr: 'прасувати' },
        { eng: 'do the washing', ukr: 'прати' },
        { eng: 'do the washing-up', ukr: 'мити посуд' },
        { eng: 'get dressed', ukr: 'одягатися' },
        { eng: 'get groceries', ukr: 'робити закупки для дому' },
        { eng: 'have a meal', ukr: 'їсти' },
        { eng: 'have tea', ukr: 'чаювати' },
        { eng: 'have supper', ukr: 'вечеряти' },
        { eng: 'negotiate', ukr: 'домовлятися' },
        { eng: 'lie in', ukr: 'залишатися в ліжку (пізніше звичайного)' },
        { eng: 'make / prepare meals', ukr: 'готувати їжу' },
        { eng: 'have / take a nap', ukr: 'передрімати' },
        { eng: 'provide (for the family)', ukr: 'забезпечувати сім\'ю' },
        { eng: 'run the home', ukr: 'вести господарство' },
        { eng: 'set off', ukr: 'рушати у дорогу' },
        { eng: 'share the chores (with sb)', ukr: 'розділяти хатні обов\'язки з кимось' },
        { eng: 'stay up late', ukr: 'не лягати спати допізна' },
        { eng: 'take the dog for a walk', ukr: 'вигулювати собаку' },
        { eng: 'take care (of children)', ukr: 'піклуватися про (дітей)' },
        { eng: 'take out garbage', ukr: 'виносити сміття' },
        { eng: 'shovel snow', ukr: 'розчищати сніг' }
      ] },
      { section: 'Food', words: [
        { eng: 'cold cuts', ukr: 'м\'ясне асорті' },
        { eng: 'game', ukr: 'дичина' },
        { eng: 'gammon', ukr: 'окіст, коптити' },
        { eng: 'ham', ukr: 'шинка' },
        { eng: 'lamb', ukr: 'м\'ясо молодого баранчика' },
        { eng: '(fatty / lean) meat', ukr: '(жирне, пісне) м\'ясо' },
        { eng: 'meatball', ukr: 'котлета' },
        { eng: 'mince', ukr: 'перекручувати' },
        { eng: 'minced meat', ukr: 'фарш' },
        { eng: 'mutton', ukr: 'баранина' },
        { eng: 'pork', ukr: 'свинина' },
        { eng: 'turkey', ukr: 'індичка' },
        { eng: 'veal', ukr: 'телятина' },
        { eng: 'venison', ukr: 'оленина' },
        { eng: 'fillet', ukr: 'філе' },
        { eng: 'haddock / perch', ukr: 'окунь' },
        { eng: 'herring', ukr: 'оселедець' },
        { eng: 'lobster', ukr: 'омар' },
        { eng: 'mackerel', ukr: 'скумбрія' },
        { eng: 'mussel', ukr: 'мідія' },
        { eng: 'oyster', ukr: 'устриця' },
        { eng: 'pike', ukr: 'щука' },
        { eng: 'prawn', ukr: 'креветка' },
        { eng: 'salmon', ukr: 'лосось' },
        { eng: 'sardine', ukr: 'сардина' },
        { eng: 'scampi', ukr: 'креветка з часником' },
        { eng: 'shellfish', ukr: 'омари, креветки' },
        { eng: 'trout', ukr: 'форель' },
        { eng: 'tuna', ukr: 'тунець' }
      ] },
      { section: 'Dairy Products', words: [
        { eng: '(mature / mild) cheese', ukr: '(витриманий, м\'який) сир' },
        { eng: 'cheese spread', ukr: 'сирна маса' },
        { eng: 'cottage cheese', ukr: 'домашній сир' },
        { eng: 'cream', ukr: 'вершки' },
        { eng: 'grated cheese', ukr: 'потертий сир' },
        { eng: '(full / semi-skimmed / skimmed) milk', ukr: '(жирне, напівзнежирене, знежирене) молоко' }
      ] },
      { section: 'Bread', words: [
        { eng: '(white / brown / wholemeal / rye) bread', ukr: '(білий, чорний, з борошна хрубого помолу, житній) хліб' },
        { eng: 'croissant', ukr: 'круасан, рогалик' },
        { eng: 'loaf (loaves) of bread', ukr: 'буханка (буханки) хліба' },
        { eng: 'pitta bread', ukr: 'лаваш' },
        { eng: 'sliced (bread / load)', ukr: 'нарізаний хліб, буханка' },
        { eng: 'biscuits / cookies', ukr: 'печиво' },
        { eng: 'whipped cream', ukr: 'збиті вершки' },
        { eng: 'crumble', ukr: 'кришити, товкти, розбивати' },
        { eng: 'have a sweet tooth', ukr: 'мати пристрасть до солодкого' }
      ] },
      { section: 'Things Added To Food', words: [
        { eng: 'mayonnaise', ukr: 'майонез' },
        { eng: 'mustard', ukr: 'гірчиця' },
        { eng: 'paprika', ukr: 'перець' },
        { eng: 'parsley', ukr: 'петрушка' },
        { eng: '(black) pepper', ukr: 'чорний перець' },
        { eng: 'salad dressing', ukr: 'заправка до салату' },
        { eng: 'spices', ukr: 'спеції' },
        { eng: 'vinegar', ukr: 'оцет' }
      ] },
      { section: 'Fruits', words: [
        { eng: 'apricot', ukr: 'абрикос' },
        { eng: 'blackberry', ukr: 'ожина' },
        { eng: 'blueberry', ukr: 'чорниця' },
        { eng: 'coconut', ukr: 'кокос' },
        { eng: '(black / red) currant', ukr: 'смородина (чорна, червона)' },
        { eng: 'gooseberry', ukr: 'агрус' },
        { eng: 'melon', ukr: 'диня' },
        { eng: 'peach', ukr: 'персик' },
        { eng: 'plum', ukr: 'слива' },
        { eng: 'raspberry', ukr: 'малина' },
        { eng: 'strawberry', ukr: 'полуниця' }
      ] },
      { section: 'Vegetables', words: [
        { eng: 'asparagus', ukr: 'спаржа' },
        { eng: 'aubergine / eggplant', ukr: 'баклажан' },
        { eng: 'cauliflower', ukr: 'цвітна капуста' },
        { eng: 'courgette / zucchini', ukr: 'кабачок' },
        { eng: 'cucumber', ukr: 'огірок' },
        { eng: 'garlic', ukr: 'часник' },
        { eng: 'leek', ukr: 'зелена цибуля' },
        { eng: 'lettuce', ukr: 'салат' },
        { eng: 'onion', ukr: 'цибуля' },
        { eng: 'parsnip', ukr: 'пастернак' },
        { eng: 'sweetcorn', ukr: 'солодка кукурудза' },
        { eng: 'turnip', ukr: 'ріпа' }
      ] },
      { section: 'Meal', words: [
        { eng: 'course', ukr: 'страва' },
        { eng: 'eat out', ukr: 'харчуватися не вдома' },
        { eng: 'helping', ukr: 'добавка, порція' },
        { eng: 'lay the table', ukr: 'накрити стіл' },
        { eng: 'snack', ukr: 'легка закуска' }
      ] },
      { section: 'Restaurant', words: [
        { eng: 'buffet car', ukr: 'вагон-буфет' },
        { eng: 'canteen', ukr: 'столова' },
        { eng: 'pub', ukr: 'пивний бар' },
        { eng: 'snack bar', ukr: 'закусочна' },
        { eng: 'take-away', ukr: 'те, що забирається додому' },
        { eng: 'beverage', ukr: 'напій' },
        { eng: 'book a table / reserve a table / make a reservation', ukr: 'замовити столик' },
        { eng: 'main course', ukr: 'основна страва' },
        { eng: 'self-service', ukr: 'самообслуговування' },
        { eng: 'service charge', ukr: 'доплата за обслуговування' },
        { eng: 'starter', ukr: 'перша страва' },
        { eng: 'waiter', ukr: 'офіціант' },
        { eng: 'waitress', ukr: 'офіціантка' }
      ] },
      { section: 'Types Of Shops', words: [
        { eng: 'butcher\'s', ukr: 'м\'ясний' },
        { eng: 'chain store', ukr: 'мережа магазинів' },
        { eng: 'chemist\'s', ukr: 'аптека' },
        { eng: 'delicatessen', ukr: 'делікатеси' },
        { eng: 'department store', ukr: 'універмаг' },
        { eng: 'designer shop', ukr: 'магазин дизайнерських виробів' },
        { eng: 'DIY store', ukr: 'магазин будівельних матеріалів' },
        { eng: 'fishmonger\'s', ukr: 'рибний' },
        { eng: 'furniture shop', ukr: 'меблевий' },
        { eng: 'greengrocer\'s', ukr: 'овочі, фрукти' },
        { eng: 'newsagent\'s', ukr: 'газетний кіоск' },
        { eng: 'off-license', ukr: 'алкоголь' },
        { eng: 'stationer\'s', ukr: 'канцтовари' }
      ] },
      { section: 'Going Shopping', words: [
        { eng: 'bargain', ukr: 'вигідна покупка' },
        { eng: 'browse', ukr: 'розглядати' },
        { eng: 'buy in the sale', ukr: 'купувати на розпродажі' },
        { eng: 'changing room', ukr: 'примірочна' },
        { eng: 'fitting room', ukr: 'кімната для примірки' },
        { eng: 'get a refund', ukr: 'отримати відшкодування' },
        { eng: 'have (sth) in stock', ukr: 'мати в асортименті' },
        { eng: 'match', ukr: 'пасувати' },
        { eng: 'out of stock', ukr: 'не бути в наявності' },
        { eng: 'sale', ukr: 'продаж' },
        { eng: 'supermarket trolley', ukr: 'візочок у супермаркеті' },
        { eng: 'till', ukr: 'каса' },
        { eng: 'too loose', ukr: 'заширокий' },
        { eng: 'can', ukr: 'бляшанка' },
        { eng: 'carton', ukr: 'картонна коробка' },
        { eng: 'jar', ukr: 'банка' },
        { eng: 'packet', ukr: 'пакет, пачка' },
        { eng: 'tin', ukr: 'консерва' }
      ] },
      { section: 'Phrasal verbs (b)', words: [
        { eng: 'back down', ukr: 'відступати, відмовлятися' },
        { eng: 'back out', ukr: 'не виконувати обіцянку' },
        { eng: 'back out of', ukr: 'ухиляти' },
        { eng: 'back up (1)', ukr: 'обгрунтувати' },
        { eng: 'back up (2)', ukr: 'підтримати' },
        { eng: 'bail out', ukr: 'виручати з біди' },
        { eng: 'bank on', ukr: 'покладатися на когось' },
        { eng: 'base on', ukr: 'базуватися на' },
        { eng: 'bear down on', ukr: 'загрозливо рухатися до когось або чогось' },
        { eng: 'bear on / upon', ukr: 'бути пов\'язаним з чимось' },
        { eng: 'bear up', ukr: 'справлятися або викручуватися з складного становища' },
        { eng: 'beat down', ukr: 'домовитися про зниження ціни' },
        { eng: 'beat up', ukr: 'калічити, бити' },
        { eng: 'become of', ukr: 'статися з' },
        { eng: 'beef up', ukr: 'підсилити' },
        { eng: 'bet on', ukr: 'довіряти, покладатися (використувується в негативному контексті)' },
        { eng: 'black out (1)', ukr: 'бути несвідомим на протязі певного часу' },
        { eng: 'black out (2)', ukr: 'викликати відстутність електроенергії' },
        { eng: 'block out', ukr: 'блокувати' },
        { eng: 'block up', ukr: 'заповнювати або блокувати вузький прохід чимось' },
        { eng: 'blow away', ukr: 'здувати' },
        { eng: 'blow out', ukr: 'задувати' },
        { eng: 'blow over', ukr: 'забуватися' },
        { eng: 'blow up (1)', ukr: 'підірвати' },
        { eng: 'blow up (2)', ukr: 'надути' },
        { eng: 'bounce back', ukr: 'бути успішним після важкого періоду' },
        { eng: 'bow out', ukr: 'покинути роботу або вид діяльності, після тривалого часу його виконання' },
        { eng: 'bowl over', ukr: 'бути приємно здивованим' },
        { eng: 'branch out', ukr: 'робити не те, що ти зазвичай робиш (про роботу)' },
        { eng: 'break away', ukr: 'відокремитись' },
        { eng: 'break down (1)', ukr: 'припиняти роботу (авто)' },
        { eng: 'break down (2)', ukr: 'не зуміти сконтролювати свої почуття і почати плакати' },
        { eng: 'break in (1)', ukr: 'робити одяг чи взуття зручним, вдягаючи їх' },
        { eng: 'break in (2)', ukr: 'перебивати' },
        { eng: 'break off', ukr: 'розірвати стосунки' },
        { eng: 'break out (1)', ukr: 'покритися' },
        { eng: 'break out (2)', ukr: 'втекти (найчастіше з в\'язниці)' },
        { eng: 'break up (1)', ukr: 'розійтись' },
        { eng: 'break up (2)', ukr: 'втрачати з\'язок' },
        { eng: 'brighten up', ukr: 'підбадьорити когось із сумним настроєм' },
        { eng: 'bring about', ukr: 'привнести' },
        { eng: 'bring along', ukr: 'взяти з собою' },
        { eng: 'bring around', ukr: 'переконати' },
        { eng: 'bring back', ukr: 'повертати спогади, нагадувати' },
        { eng: 'bring down', ukr: 'обезсилити' },
        { eng: 'bring forward', ukr: 'змінити час проведення події на раніше' },
        { eng: 'bring in', ukr: 'ухвалити' },
        { eng: 'bring off', ukr: 'досягти успіху' },
        { eng: 'bring on', ukr: 'спричиняти (проблеми)' },
        { eng: 'bring out', ukr: 'виробляти, випускати у продаж' },
        { eng: 'bring up (1)', ukr: 'виховувати, ростити (дітей)' },
        { eng: 'bring up (2)', ukr: 'обговорювати, піднімати тему' },
        { eng: 'brush up', ukr: 'практикувати, покращувати знання або навички в чомусь' },
        { eng: 'budget for', ukr: 'розрахувати бюджет' },
        { eng: 'build on', ukr: 'дороблювати або працювати над чимось' },
        { eng: 'build up', ukr: 'будувати, нарощувати, наповнювати' },
        { eng: 'burn out (informal)', ukr: 'вигорати' },
        { eng: 'butt in', ukr: 'переривати розмову або діяльність, вставляти зайві 5 копійок' }
      ] },
      { section: 'Phrasal verbs (c)', words: [
        { eng: 'clamp down', ukr: 'спробувати зупинити погану, нелегальну або шкідливу діяльність людей' },
        { eng: 'clean up', ukr: 'прибрати' },
        { eng: 'clear off (informal)', ukr: 'йти геть' },
        { eng: 'clear out', ukr: 'робити місце чистим і акуратним' },
        { eng: 'clear up (1)', ukr: 'випогоджуватись' },
        { eng: 'clear up (2)', ukr: 'вирішувати конфлікт або проблему' },
        { eng: 'cling to', ukr: 'вчепитися' },
        { eng: 'clog up', ukr: 'заблокувати прохід' },
        { eng: 'close down', ukr: 'закрити' },
        { eng: 'close in', ukr: 'наближуватись' },
        { eng: 'clown around', ukr: 'робити дурниці аби розсмішити інших' },
        { eng: 'combine with', ukr: 'поєднати' },
        { eng: 'come about', ukr: 'зародитися' },
        { eng: 'come across (1)', ukr: 'раптово наштовхнутися' },
        { eng: 'come across (2)', ukr: 'на вигляд' },
        { eng: 'come along (1)', ukr: 'піти разом' },
        { eng: 'come along (2)', ukr: 'прогресувати, покращуватись' },
        { eng: 'come apart', ukr: 'коли річ відокремлюється на окремі частинки внаслідок поганого стану' },
        { eng: 'come around / round', ukr: 'змінити думку' },
        { eng: 'come around', ukr: 'прийти' },
        { eng: 'come away', ukr: 'змінитися після певної ситуації' },
        { eng: 'come back to', ukr: 'мати справу з чимось, з чим мав раніше' },
        { eng: 'come by', ukr: 'отримати щось, що важко дістати' },
        { eng: 'come down to', ukr: 'залежати' },
        { eng: 'come down with', ukr: 'захворіти' },
        { eng: 'come in for', ukr: 'бути звинувачиним і критикованим' },
        { eng: 'come into', ukr: 'успадкувати' },
        { eng: 'come of', ukr: 'вийти (результат)' },
        { eng: 'come off (1)', ukr: 'розкритись' },
        { eng: 'come off (2)', ukr: 'спрацювати' },
        { eng: 'dadwada', ukr: 'awdadawda' },
        { eng: 'dadwada', ukr: 'awdadawda' },
        { eng: 'dadwada', ukr: 'awdadawda' },
        { eng: 'dadwada', ukr: 'awdadawda' },
        { eng: 'dadwada', ukr: 'awdadawda' },
        { eng: 'dadwada', ukr: 'awdadawda' }
      ] },
      { section: 'WEC Unit1', words: [
        { eng: 'job (n)', ukr: 'the work sb does to earn money, employment' },
        { eng: 'occupation (n)', ukr: 'a person’s regular work or profession' },
        { eng: 'work (n)', ukr: 'occupation or profession / particular tasks sb has to do in their job / the place where sb does their job' },
        { eng: 'employment (n)', ukr: 'work, esp. in return for regular payment' },
        { eng: 'profession (n)', ukr: ' job requiring advanced education or training' },
        { eng: 'at work (n)', ukr: 'at one’s job or place of employment / in action' },
        { eng: 'out of work (n)', ukr: 'jobless, unemployed' },

        { eng: 'task (n)', ukr: 'activity sb has to do, usually as a part of a larger project' },
        { eng: 'course (n)', ukr: 'series of lessons or lectures on a particular subject' },
        { eng: 'duty (n)', ukr: 'what sb has to do for their job' },

        { eng: 'employer (n)', ukr: 'person, firm that hires workers' },
        { eng: 'employee (n)', ukr: 'a person who is paid to work for an organisation or for another person' },
        { eng: 'colleague (n)', ukr: 'a person you work with (at a professional job)' },
        { eng: 'assistant (n)', ukr: 'person who helps sb in their job' },
        { eng: 'clerk (n)', ukr: 'person who works in an office or shop and keeps records, files, accounts etc.' },
        { eng: '(army) officer (n)', ukr: 'person appointed to command others in the armed forces' },
        { eng: 'attendant (n)', ukr: 'person whose job is to provide a service in a public place' },

        { eng: 'party (n)', ukr: 'a group of people working or travelling together' },
        { eng: 'crew (n)', ukr: 'people who work on a ship or aircraft' },
        { eng: 'staff (n)', ukr: 'people who work for a company or organisation, employees' },

        { eng: 'aim (n)', ukr: 'a purpose, an intention' },
        { eng: 'goal (n)', ukr: 'sth that you hope to achieve esp. when much time and effort is needed' },
        { eng: 'intention (n)', ukr: 'sth which sb plans to do' },
        { eng: 'challenge (n)', ukr: 'a difficult task that tests sb’s ability' },
        { eng: 'success (n)', ukr: 'achievement of a desired aim' },
        { eng: 'ambition (n)', ukr: 'a strong desire for success or distinction' },

        { eng: 'achieve (v)', ukr: 'to succeed in doing sth, accomplish, especially after a lot of effort' },
        { eng: 'fulfil (v)', ukr: 'bring about the completion or achievement of a desired promise etc.' },
        { eng: 'cope (with) (v)', ukr: 'to deal successfully with sth difficult' },
        { eng: 'deal with (phr.v.)', ukr: 'act in order to solve a problem or make a decision about a situation' },
        { eng: 'face (v)', ukr: 'confront, have to deal with a difficult situation' },
        { eng: 'succeed (in) (v)', ukr: 'to manage to do sth, achieve your goals' },

        { eng: 'manage (v)', ukr: 'to be in charge of' },
        { eng: 'run (v)', ukr: 'be in charge of a shop or business' },
        { eng: 'operate (v)', ukr: 'function or cause to function' },
        { eng: 'undertake (v)', ukr: 'to make oneself responsible for sth' },

        { eng: 'skills (n)', ukr: 'the ability to do sth very well' },
        { eng: 'qualities (n)', ukr: 'usually good characteristics' },
        { eng: 'qualifications (n)', ukr: 'a quality or skill that makes sb suitable for a particular job' },
        { eng: 'experience (n)', ukr: '1) sth that happens to you or sth that you do 2) the knowledge you have acquired' }
      ] },
      { section: 'WEC Unit2', words: [
        { eng: 'look through (v)', ukr: 'to read, examine' },
        { eng: 'look at (v)', ukr: 'to turn your eyes to a particular direction' },
        { eng: 'see (v)', ukr: 'notice, observe, take a look at sb/sth' },
        { eng: 'watch (v)', ukr: 'to look at sb/sth for a period of time and pay attention to what is happening' },
        { eng: 'notice (v)', ukr: 'to become aware of sb/sth' },
        { eng: 'regard (v)', ukr: 'look at sth' },
        { eng: 'stare at (v)', ukr: ' look at sb/sth for a long time (often rudely or impolitely)' },
        { eng: 'glance at (v)', ukr: 'to take a quick look at sth' },
        { eng: 'observe (v)', ukr: 'to see or notice something' },

        { eng: 'find out (v)', ukr: 'to learn sth you didn\'t know, especially through deliberate effort' },
        { eng: 'invent (v)', ukr: 'create or make up sth for the first time' },
        { eng: 'discover (v)', ukr: 'become aware of sth you didn\'t know before' },
        { eng: 'detect (v)', ukr: 'notice, recognise that sth is present' },

        { eng: 'explore (v)', ukr: 'investigate sth (a place or scientific field) systematically, in order to find out more facts about it' },
        { eng: 'investigate (v)', ukr: 'to discover and examine all the facts about sth' },
        { eng: 'look for (v)', ukr: 'to search for or try to find sb/sth' },
        { eng: 'look up (v)', ukr: 'find out by looking in a reference book' },
        { eng: '(do) research (v)', ukr: 'careful study or investigation, esp. to discover new information' },

        { eng: 'attempt (n)', ukr: 'an act of trying to do sth, esp. when this is unsuccessful' },
        { eng: 'effort (n)', ukr: 'the use of much physical or mental energy to do sth' },
        { eng: 'trial (n)', ukr: '1) a formal examination of evidence in a law court 2) a test of quality' },
        { eng: 'experiment (n)', ukr: 'a scientific test done to discover what happens to sth in particular conditions' },

        { eng: 'audience (n)', ukr: 'a group of people watching or listening to a play, concert, film etc.' },
        { eng: 'spectators (n)', ukr: 'people who watch sth, especially a sporting event' },
        { eng: 'viewers (n)', ukr: 'people who watch television' },
        { eng: 'sightseers (n)', ukr: 'people who visit places of interest as tourists' },
        { eng: 'onlookers (n)', ukr: 'people who watch sth happening without getting involved' },
        { eng: 'witness (n)', ukr: 'a person who sees an event and is able to tell other people what happened' },

        { eng: 'memorise (v)', ukr: 'learn sth well enough to remember it exactly' },
        { eng: 'remind (sb of sth) (v)', ukr: 'to make sb remember sth' },
        { eng: 'recall (v)', ukr: 'to bring sth back to mind, remember' },
        { eng: 'recognise (v)', ukr: 'be able to identify sb/sth' },

        { eng: 'view (n)', ukr: '1) opinion 2) a scene, esp. of a fine tract of countryside' },
        { eng: 'sight (n)', ukr: 'a thing that one sees or can see / places of interest in a town or city, that are often visited by tourists' },
        { eng: 'image (n)', ukr: 'a mental picture vision' },
        { eng: 'vision (n)', ukr: 'the ability to see' },
        { eng: 'scene (n)', ukr: 'the place where an action or event occurs' }
      ] },
      { section: 'WEC Unit3', words: [
        { eng: 'rise (v)', ukr: 'move upwards, stand up' },
        { eng: 'raise (v)', ukr: 'support by collecting money' },
        { eng: 'arise (v)', ukr: 'begin to exist or become known to people (for a situation or problem)' },
        { eng: 'lift (v)', ukr: 'raise sb / sth to a higher position or level' },

        { eng: 'grow (v)', ukr: 'increase in size or quantity' },
        { eng: 'grow up (v)', ukr: 'reach the stage of full development' },
        { eng: 'bring up (v)', ukr: 'to care for and raise (a child)' },
        { eng: 'become (v)', ukr: 'develop into / grow to be' },

        { eng: 'educate (v)', ukr: 'teach sb over a period of time at school, university etc.' },
        { eng: 'learn (v)', ukr: 'gain knowledge or a skill by study' },
        { eng: 'teach (v)', ukr: 'give lessons in (sb) / show sb how to do sth' },
        { eng: 'study (v)', ukr: 'to give one’s time and attention to learning about a subject' },
        { eng: 'read (v)', ukr: 'to look at and understand the written or printed word' },
        { eng: 'instruct (v)', ukr: 'to give orders or directions to sb' },

        { eng: 'behaviour (n)', ukr: 'social conduct, the way a person or an animal behaves' },
        { eng: 'attitude (n)', ukr: 'the opinions and feelings that you usually have about sth' },
        { eng: 'temper (n)', ukr: 'state of mind regarding being angry or being calm' },
        { eng: 'mood (n)', ukr: 'the way sb feels at a particular time' },
        { eng: 'manner (n)', ukr: 'the way sb behaves, their social conduct' },
        { eng: 'manners (n)', ukr: 'ways of behaving in social situations' },

        { eng: 'familiar with / to (adj)', ukr: 'knowing sth well and understanding it' },
        { eng: 'accustomed to (adj)', ukr: 'to be used to sth' },
        { eng: 'aware of (adj)', ukr: 'knowing sth' },

        { eng: 'custom (n)', ukr: 'sth that is done by people in a particular society because it is traditional' },
        { eng: 'habit (n)', ukr: 'sth you do often or regularly' },
        { eng: 'fashion (n)', ukr: 'popular style of clothes, hair etc. at a particular time or place' },
        { eng: 'trend (n)', ukr: 'a general tendency or direction' },
        { eng: 'routine (n)', ukr: 'the usual series of things sb does regularly at a particular time' },

        { eng: 'common (adj)', ukr: 'ordinary, frequently encountered or often happening' },
        { eng: 'ordinary (adj)', ukr: 'average, not different or special' },
        { eng: 'usual (adj)', ukr: 'happening most often in a particular situation' },
        { eng: 'normal (adj)', ukr: 'regular, ordinary, in accordance with what people expect' },
        { eng: 'regular (adj)', ukr: 'done or happening often, frequent' },

        { eng: 'eager (adj)', ukr: 'full of interest or desire' },
        { eng: 'keen (on / to) (adj)', ukr: 'eager, enthusiastic, very much wanting to do sth' },
        { eng: 'enthusiastic (about) (adj)', ukr: 'showing great interest in sth' },
        { eng: 'interested in (adj)', ukr: 'showing curiosity, concern or desire to learn more about sth because you think it is important' },
        { eng: 'willing to (adj)', ukr: 'ready and wanting to help or do sth' }
      ] },
      { section: 'WEC Unit4', words: [
        { eng: 'travel (v)', ukr: 'to go from one place to another' },
        { eng: 'transfer (to) (v)', ukr: 'to cause sb or sth to move from one place to another' },
        { eng: 'transport (v)', ukr: 'take goods, people etc. from one place to another in a vehicle' },
        { eng: 'transmit (v)', ukr: 'to send out electric signals etc. by radio' },

        { eng: 'arrive (in /at) (v)', ukr: 'get to a place at the end of a journey' },
        { eng: 'get (to) (v)', ukr: 'arrive at a place' },
        { eng: 'reach (v)', ukr: 'to get, to arrive at' },
        { eng: 'come (v)', ukr: 'to move to, towards or into a place (where the speaker is)' },
        { eng: 'approach (v)', ukr: 'to get closer to sb or sth (in place or time)' },
        { eng: 'appear (v)', ukr: 'to start to be seen or suddenly be seen' },

        { eng: 'carry (v)', ukr: 'to take sth somewhere in your hands or arms, on your back etc.' },
        { eng: 'fetch (v)', ukr: 'to go and bring sth from the place where it is' },
        { eng: 'deliver (to) (v)', ukr: 'to convey, carry sth to a destination' },

        { eng: 'voyage (n)', ukr: 'a long journey by ship or spacecraft' },
        { eng: 'journey (n)', ukr: 'when you travel from one place to another' },
        { eng: 'trip (n)', ukr: 'a short journey to a place and back again' },
        { eng: 'tour (n)', ukr: 'an organised trip during which you visit different places' },
        { eng: 'excursion (n)', ukr: 'a short journey made for a particular purpose' },
        { eng: 'travel (n)', ukr: 'the act of taking a journey' },
        { eng: 'expedition (n)', ukr: 'a long journey, esp. one made by a group of people with a particular aim' },
        { eng: 'flight (n)', ukr: 'a journey in a plane or space vehicle' },
        { eng: 'cruise (n)', ukr: 'a holiday on a large ship' },

        { eng: 'address (n)', ukr: 'the number of the building and the name of the street and town etc. where someone lives or works' },
        { eng: 'road (n)', ukr: 'a specially prepared hard surface for cars, buses etc. to travel on' },
        { eng: 'street (n)', ukr: 'a public road in a city or town that usually has buildings on its side(s)' },
        { eng: 'way (n)', ukr: 'a route / road etc. taken in order to reach a place' },
        { eng: 'direction (n)', ukr: 'the way sth or sb moves, faces or is aimed / information or instructions about what to do or where to go' },
        { eng: 'route (n)', ukr: 'the way from one place to another' },
        { eng: 'path (n)', ukr: 'a track that people walk along over an area or ground' },

        { eng: 'site (n)', ukr: 'a place where a building, town etc. was, is or will be situated' },
        { eng: 'position (n)  ', ukr: 'where sb or sth is in relation to other things' },
        { eng: 'location (n)', ukr: 'the place where sth happens or is situated' },
        { eng: 'point (n)', ukr: 'a particular place or position where sth takes place' },
        { eng: 'place (n)', ukr: 'a point, building or area' },
        { eng: 'room (n)', ukr: 'empty space for people or things to be fitted in' },
        { eng: 'space (n)', ukr: 'an area of any size that is empty or available for use' },

        { eng: 'foreign (adj)', ukr: 'not from your own country or the country you are talking about' },
        { eng: 'strange (adj)', ukr: 'unusual, not familiar' },
        { eng: 'different (from / to) (adj)', ukr: 'not the same' },
        { eng: 'peculiar (adj)', ukr: 'odd or strange, esp. in an unpleasant way' },
        { eng: 'curious (adj)', ukr: 'eager to know or learn' },
      ] },
      { section: 'WEC Unit6', words: [
        { eng: 'borrow (v)', ukr: 'take sth from sb with their permission, intending to return it in the future' },
        { eng: 'lend (v)', ukr: 'allow sb to use sth that you own for a period of time' },
        { eng: 'let (v)', ukr: 'allow the use of your property in exchange for money' },
        { eng: 'hire (v)', ukr: 'pay money to the owner of sth in order to use it for a period of time / employ sb to do a particular job for you' },
        { eng: 'rent (v)', ukr: 'to have and use sth which does not belong to you in exchange for a sum of money that you pay regularly' },

        { eng: 'spend (v)', ukr: '1) to use your money to buy or pay for things 2) to pass or use time' },
        { eng: 'waste (v)', ukr: 'using too much of something (money, time etc.) unnecessarily' },
        { eng: 'save (v)', ukr: 'gradually collect money by spending less than you get, usually to buy sth you want' },
        { eng: 'afford (n)', ukr: 'to have enough money, time etc. for a particular purpose' },

        { eng: 'bill (n)', ukr: 'a written statement of money that you owe for goods / services' },
        { eng: 'fare (n)', ukr: 'the price you pay to travel by bus, train, plane etc.' },
        { eng: 'fee (n)', ukr: 'an amount of money that you pay to a professional person or organisation for their work' },
        { eng: 'fine (n)', ukr: 'punishment in which sb has to pay a sum of money because they have done sth wrong or broken a rule' },
        { eng: 'ticket (n)', ukr: '1) a printed piece of paper showing that a person has paid to travel on a bus, plane, etc. or to enter a cinema, concert hall etc. 2) an official note given for a traffic offence' },
        { eng: 'receipt (n)', ukr: 'a piece of paper that you get from sb as confirmation that they have received money or goods from you' },
        { eng: 'account (n)', ukr: 'a written statement of money paid or owed for goods and services' },
        { eng: 'discount (n)', ukr: 'a reduction in the cost of goods that you are buying' },
        { eng: 'tax (n)', ukr: 'money that you pay to the government according to your income' },

        { eng: 'salary (n)', ukr: 'fixed regular payment, usually made every month to employees' },
        { eng: 'wage(s) (n)', ukr: 'regular payment, on hourly, daily, weekly basis' },
        { eng: 'payment (n)', ukr: 'a sum of money paid' },
        { eng: 'a sum of money paid', ukr: 'money one earns or receives' },
        { eng: 'bonus (n)', ukr: 'a payment added to what is usual or expected' },
        { eng: 'allowance (n)', ukr: 'money given to sb on a regular basis (e.g. as pocket money)' },
        { eng: 'award (n)', ukr: 'prize / gift / trophy' },
        { eng: 'reward (n)', ukr: 'a thing that is given or received in return for doing sth good' },
        { eng: 'donation (n)', ukr: 'contribution to a charity or other organisation' },

        { eng: 'owe (v)', ukr: 'to have an obligation to pay sb a certain amount' },
        { eng: 'own (v)', ukr: 'to have as one’s possession' },
        { eng: 'possess (v)', ukr: 'to have (an ability)' },
        { eng: 'keep (v)', ukr: 'continue to have or hold sth' },
        { eng: 'belong to (v)', ukr: 'to be the property of' },

        { eng: 'price (n)', ukr: 'the amount of money which sth is bought or sold for' },
        { eng: 'prize (n)', ukr: 'an award given to the winner of a competition, race etc.' },
        { eng: 'charge (n)', ukr: 'amount of money sb has to pay for a service or to buy sth' },
        { eng: 'value (n)', ukr: 'how much sth is worth' },
        { eng: 'bargain (n)', ukr: 'sth bought cheaply or for less than its usual price' },
        { eng: 'worth (adj.)', ukr: 'having a certain value /(n) = the value, usefulness or importance of sth' },
        { eng: 'tip (n)', ukr: 'extra money given to sb (eg a waiter, porter etc.) in order to thank them for their service' },

        { eng: 'precious (adj.)', ukr: 'of great value or importance because of being very beautiful, rare or expensive' },
        { eng: 'valuable (adj.)', ukr: 'worth a lot of money / very useful or important' },
        { eng: 'priceless (adj.)', ukr: 'too valuable to be priced or extremely expensive' },
        { eng: 'worthless (adj.)', ukr: 'having no value, importance or use' },
        { eng: 'economic (adj.)', ukr: 'connected with trade, industry and the management of money' },
        { eng: 'economical (adj.)', ukr: 'using money, time, goods etc. carefully and without wasting any' },
        { eng: 'financial (adj.)', ukr: 'connected with money or the management of money' },

        { eng: 'loan (n)', ukr: 'money that you borrow (usually from a bank)' },
        { eng: 'debt (n)', ukr: 'amount of money that you owe to a person / bank' },
        { eng: 'sum (n)', ukr: 'a quantity, esp. of money' },
        { eng: 'amount (n)', ukr: 'a quantity of money, time or a substance' },
        { eng: 'deposit (n)', ukr: '1) to pay part of a larger sum the rest of which is to be paid later 2) to put money into a bank' },
        { eng: 'instalment (n)', ukr: 'a small sum of money paid at regular intervals over a period of time, rather than paying the whole amount at once' },
        { eng: 'budget (n)', ukr: ' plan of how a person or organisation will spend the money that is available in a particular period of time' },

        { eng: 'cheque (n)', ukr: 'a printed form that you can sign and use instead of money' },
        { eng: 'cash (n)', ukr: 'money in the form of coins or notes' },
        { eng: 'coins (n)', ukr: 'money made of metal' },
        { eng: 'currency (n)', ukr: 'the money used in a particular country' },
        { eng: '(bank) notes (n)', ukr: 'paper money' },
        { eng: 'change (n)', ukr: 'coins / money that you receive when you pay for sth with more money than it costs because you do not have the exact amount of money' }
      ] },
      { section: 'WEC Unit7', words: [
        { eng: 'think (of/about) (v)', ukr: 'have an opinion / impression about sth' },
        { eng: 'consider (v)', ukr: 'think carefully about sth / have an opinion about sth' },
        { eng: 'regard (v)', ukr: 'believe that sb or sth has a particular quality' },
        { eng: 'believe (v)', ukr: 'to be sure that sth is true or that sb is telling the truth' },
        { eng: 'mean (v)', ukr: '1) explain what you wish to say 2) intend' },

        { eng: 'realise (v)', ukr: 'to become aware that sth is true, understand it' },
        { eng: 'understand (v)', ukr: 'to know the meaning of what sb is telling you, or the language that they speak' },
        { eng: 'recognise (v)', ukr: 'to know who a person or what a thing is' },
        { eng: 'meet (v)', ukr: 'to become familiar with sb for the first time' },
        { eng: 'introduce (v)', ukr: 'to present (sb) by name (to another person)' },
        { eng: 'present (v)', ukr: 'to appear in and introduce a programme on radio or television' },
        { eng: 'appreciate (v)', ukr: 'to recognise and enjoy the good qualities of sth / to be grateful for sth' },

        { eng: 'assume (v)', ukr: 'to take for granted (to believe sth to be true without proof)' },
        { eng: 'guess (v)', ukr: 'to make an estimate or conclusion you are not sure of, without knowledge' },
        { eng: 'suppose (v)', ukr: '1) to think that sth is true or probable 2) to be expected or required to do sth' },
        { eng: 'estimate (v)', ukr: 'to form a rough or general idea of sth' },
        { eng: 'calculate (v)', ukr: 'to estimate sth by using numbers or one’s judgement' },
        { eng: 'predict (v)', ukr: 'to say in advance that sth will happen' },

        { eng: 'idea (n)', ukr: '1) knowledge or understanding of something without being certain (n) = 2) a suggestion, thought or plan for doing something' },
        { eng: 'view (n)', ukr: 'opinion' },
        { eng: 'thought (n)', ukr: 'idea' },
        { eng: 'point (n)', ukr: 'single fact, idea or opinion' },
        { eng: 'aspect (n)', ukr: 'a distinct feature or element in a problem, situation etc.' },
        { eng: 'respect (n)', ukr: 'politeness and honour shown towards sb or sth' },
        { eng: 'matter (of fact) (phrase)', ukr: 'actually, in fact' },

        { eng: 'queue (n)', ukr: 'a line of people or vehicles waiting for sth' },
        { eng: 'line (n)', ukr: 'a number of people / things one behind the other or standing side by side' },
        { eng: 'aisle (n)', ukr: 'a long narrow gap between rows of seats (in a church, classroom etc.) or between supermarket shelves' },
        { eng: 'corridor (n)', ukr: 'a passage in a building or train, usually with rooms on either side' },
        { eng: 'hall (n)', ukr: 'a room serving as an entry area' },
        { eng: 'row (n)', ukr: 'a number of people / things standing or arranged in a line' },

        { eng: 'available (adj.)', ukr: 'that can be found or obtained' },
        { eng: 'spare (adj.)', ukr: 'extra, additional, available for use when needed' },
        { eng: 'free (adj.)', ukr: 'not being used / occupied by sb or not reserved for somebody to use (e.g. table, seat) / costing nothing' },
        { eng: 'convenient (adj.)', ukr: 'easy, useful or suitable for a particular situation' },
        { eng: 'handy (adj.)', ukr: 'useful for a particular purpose' },
        { eng: 'usable (adj.)', ukr: 'that can be used' },

        { eng: 'absence (n)', ukr: 'the state of not being somewhere' },
        { eng: 'lack (n)', ukr: 'when something is insufficient or does not exist at all' },
        { eng: 'shortage (n)', ukr: 'deficiency, when there is not enough of sth' },
        { eng: 'loss (n)', ukr: 'the fact of no longer having sth or having less of it' },

        { eng: 'short (of sth) (adj.)', ukr: 'not have enough of sth, nearly run out of' },
        { eng: 'scarce (adj.)', ukr: 'not easy to find or obtain' },
        { eng: 'rare (adj.)', ukr: 'not common' },
        { eng: 'inadequate (adj.)', ukr: 'too low in quality, or too small in amount; not good enough' },
        { eng: 'insufficient (adj.)', ukr: ' inadequate, not enough for a particular purpose' }
      ] },
      { section: 'Наголоси (А)', words: [
        { eng: 'абиде', ukr: 'абИде' },
        { eng: 'абиколи', ukr: 'абИколи' },
        { eng: 'агрономія', ukr: 'агронОмія' },
        { eng: 'адже', ukr: 'аджЕ' },
        { eng: 'алкоголь', ukr: 'алкогОль' },
        { eng: 'алфавіт', ukr: 'алфАвІт' },
        { eng: 'аніж', ukr: 'анІж' },
        { eng: 'аркушик', ukr: 'Аркушик' },
        { eng: 'асиметрія', ukr: 'асиметрІя' }
      ] },
      { section: 'Наголоси (Б)', words: [
        { eng: 'багаторазовий', ukr: 'багаторазОвий' },
        { eng: 'байдуже', ukr: 'бАйдУже' },
        { eng: 'барометр', ukr: 'барОметр' },
        { eng: 'бездоганний', ukr: 'бездогАнний' },
        { eng: 'безпринципний', ukr: 'безпринцИпний' },
        { eng: 'бешкет', ukr: 'бЕшкет' },
        { eng: 'благовіст', ukr: 'блАговіст' },
        { eng: 'близький', ukr: 'близькИй' },
        { eng: 'болотистий', ukr: 'болотИстий' },
        { eng: 'бородавка', ukr: 'борОдавка' },
        { eng: 'босоніж', ukr: 'босОніж' },
        { eng: 'боязнь', ukr: 'боЯзнь' },
        { eng: 'будемо', ukr: 'бУдемо' },
        { eng: 'бурштиновий', ukr: 'бурштинОвий' },
        { eng: 'бюлетень', ukr: 'бюлетЕнь' }
      ] },
      { section: 'Наголоси (В)', words: [
        { eng: 'ваги', ukr: 'вАги' },
        { eng: 'валовий', ukr: 'валовИй' },
        { eng: 'вантажівка', ukr: 'вантажІвка' },
        { eng: 'везла', ukr: 'везлА' },
        { eng: 'веретено', ukr: 'веретЕно' },
        { eng: 'вершковий', ukr: 'вершкОвий' },
        { eng: 'весняний', ukr: 'веснЯнИй' },
        { eng: 'вести', ukr: 'вестИ' },
        { eng: 'взірцевий', ukr: 'взірцЕвий' },
        { eng: 'вигода (користь)', ukr: 'вИгода (користь)' },
        { eng: 'вигода (зручність)', ukr: 'вигОда (зручність)' },
        { eng: 'видання (від дієсл.)', ukr: 'видАння (від дієсл.)' },
        { eng: 'видання (про дівчат)', ukr: 'виданнЯ (про дівчат)' },
        { eng: 'виделка', ukr: 'видЕлка' },
        { eng: 'вимова', ukr: 'вимОва' },
        { eng: 'вимога', ukr: 'вимОга' },
        { eng: 'випадок', ukr: 'вИпадок' },
        { eng: 'виразний', ukr: 'вирАзний' },
        { eng: 'висіти', ukr: 'вИсІти' },
        { eng: 'витрата', ukr: 'вИтрата' },
        { eng: 'вишиваний', ukr: 'вишИваний' },
        { eng: 'вишиванка', ukr: 'вишИвАнка' },
        { eng: 'відвезти', ukr: 'відвезтИ' },
        { eng: 'відвести', ukr: 'відвестИ' },
        { eng: 'відгомін', ukr: 'вІдгомін' },
        { eng: 'відмінний', ukr: 'відмІнний' },
        { eng: 'віднести', ukr: 'віднестИ' },
        { eng: 'відомість (документ)', ukr: 'вІдомість (документ)' },
        { eng: 'відомість (повідомлення, дані, популярність)', ukr: 'відОмість (повідомлення, дані, популярність)' },
        { eng: 'віршовий', ukr: 'віршовИй' },
        { eng: 'вітчим', ukr: 'вітчИм' }
      ] },
      { section: 'Наголоси (Г)', words: [
        { eng: 'гальмО', ukr: 'гальмО' },
        { eng: 'гАльма (мн. Н.в.)', ukr: 'гАльма (мн. Н.в.)' },
        { eng: 'гальмА (одн. Р.в.)', ukr: 'гальмА (одн. Р.в.)' },
        { eng: 'генЕзис', ukr: 'генЕзис' },
        { eng: 'глЕчик', ukr: 'глЕчик' },
        { eng: 'глИбоко', ukr: 'глИбоко' },
        { eng: 'глядАч', ukr: 'глядАч' },
        { eng: 'горошИна', ukr: 'горошИна' },
        { eng: 'громАдський', ukr: 'громАдський' },
        { eng: 'граблІ', ukr: 'граблІ' },
        { eng: 'грошей', ukr: 'грОшей' },
        { eng: 'гуртожиток', ukr: 'гуртОжитокгуртОжиток' },
        { eng: 'гуртом', ukr: 'гуртОм' }
      ] },
      { section: 'Наголоси (Д)', words: [
        { eng: 'данина', ukr: 'данИна' },
        { eng: 'дано', ukr: 'дАно' },
        { eng: 'дециметр', ukr: 'децимЕтр' },
        { eng: 'дешевий', ukr: 'дешЕвий' },
        { eng: 'дещиця', ukr: 'дЕщиця' },
        { eng: 'деякий', ukr: 'дЕякий' },
        { eng: 'джерело', ukr: 'джерелО' },
        { eng: 'дивлячись', ukr: 'дИвлячись' },
        { eng: 'дичавіти', ukr: 'дичАвіти' },
        { eng: 'діалог', ukr: 'діалОг' },
        { eng: 'дітьми', ukr: 'дІтьми' },
        { eng: 'добовий', ukr: 'добовИй' },
        { eng: 'добуток', ukr: 'добУток' },
        { eng: 'довезти', ukr: 'довезтИ' },
        { eng: 'довершений', ukr: 'довЕршений' },
        { eng: 'довідник', ukr: 'довІдник' },
        { eng: 'догмат', ukr: 'дОгмат' },
        { eng: 'документ', ukr: 'докумЕнт' },
        { eng: 'долілиць', ukr: 'долІлиць' },
        { eng: 'долішній', ukr: 'дОлішній' },
        { eng: 'донести', ukr: 'донестИ' },
        { eng: 'донька', ukr: 'дОнька' },
        { eng: 'досконалий', ukr: 'досконАлий' },
        { eng: 'дочка', ukr: 'дочкА' },
        { eng: 'дощечка', ukr: 'дОщечка' },
        { eng: 'дрова', ukr: 'дрОва' }
      ] },
      { section: 'Наголоси (Е, Є, Ж, І)', words: [
        { eng: 'експерт', ukr: 'експЕрт' },
        { eng: 'єретик', ukr: 'єретИк' },
        { eng: 'жадоба', ukr: 'жадОба' },
        { eng: 'жалюзі', ukr: 'жалюзІ' },
        { eng: 'жаркий', ukr: 'жаркИй' },
        { eng: 'живопис', ukr: 'живОпис' },
        { eng: 'індустрія', ukr: 'індУстрія' }
      ] },
      { section: 'Наголоси (К)', words: [
        { eng: 'кавун', ukr: 'кавУн' },
        { eng: 'камбала', ukr: 'кАмбала' },
        { eng: 'каталог', ukr: 'каталОг' },
        { eng: 'квартал', ukr: 'квартАл' },
        { eng: 'кидати', ukr: 'кИдати' },
        { eng: 'кишка', ukr: 'кИшка' },
        { eng: 'кілометр', ukr: 'кіломЕтр' },
        { eng: 'кінчити', ukr: 'кінчИти' },
        { eng: 'книжки (множ.)', ukr: 'книжкИ (множ.)' },
        { eng: 'колесо', ukr: 'кОлесо' },
        { eng: 'колія', ukr: 'кОлія' },
        { eng: 'контрактовий', ukr: 'контрактОвий' },
        { eng: 'копчений (дієприкметник)', ukr: 'кОпчений (дієприкметник)' },
        { eng: 'копчЕний (прикметник)', ukr: 'копчЕний (прикметник)' },
        { eng: 'корисний', ukr: 'кОрИсний' },
        { eng: 'косий', ukr: 'кОсий' },
        { eng: 'котрий', ukr: 'котрИй' },
        { eng: 'кроїти', ukr: 'крОїти' },
        { eng: 'кропива', ukr: 'кропивА' },
        { eng: 'кулінарія', ukr: 'кулінАрія' },
        { eng: 'курятина', ukr: 'кУрятина' }
      ] },
      { section: 'Наголоси (Л)', words: [
        { eng: 'лате', ukr: 'лАте' },
        { eng: 'легкий', ukr: 'легкИй' },
        { eng: 'листопад', ukr: 'листопАд' },
        { eng: 'літопис', ukr: 'літОпис' },
        { eng: 'локшина', ukr: 'лОкшина' },
        { eng: 'льодовий', ukr: 'льодовИй' },
        { eng: 'люблю', ukr: 'люблЮ' },
        { eng: 'люстро', ukr: 'лЮстро' }
      ] },
      { section: 'Наголоси (М)', words: [
        { eng: 'мабуть', ukr: 'мАбУть' },
        { eng: 'магістерський (про вчений ступінь)', ukr: 'магістЕрський (про вчений ступінь)' },
        { eng: 'маркетинг', ukr: 'мАркетинг' },
        { eng: 'мережа', ukr: 'мерЕжа' },
        { eng: 'металургія', ukr: 'металУргія' },
        { eng: 'міліметр', ukr: 'мілімЕтр' },
        { eng: 'мозолистий', ukr: 'мозолИстий' },
        { eng: 'монолог', ukr: 'монолОг' },
        { eng: 'м’ясоїд', ukr: 'м’ясОїд' }
      ] },
      { section: 'Наголоси (Н)', words: [
        { eng: 'навчання', ukr: 'навчАння' },
        { eng: 'на добраніч', ukr: 'на добрАніч' },
        { eng: 'налигач', ukr: 'налИгач' },
        { eng: 'нанести', ukr: 'нанестИ' },
        { eng: 'начинка', ukr: 'нАчинка' },
        { eng: 'невибагливий', ukr: 'невибАгливий' },
        { eng: 'недруг', ukr: 'нЕдруг' },
        { eng: 'ненавидіти', ukr: 'ненАвидіти' },
        { eng: 'ненависний', ukr: 'ненАвисний' },
        { eng: 'ненависть', ukr: 'ненАвисть' },
        { eng: 'нести', ukr: 'нестИ' },
        { eng: 'нехитрий', ukr: 'нехИтрий' },
        { eng: 'ніздря', ukr: 'нІздря' },
        { eng: 'новий', ukr: 'новИй' }
      ] }
    ],
    select: { isChosen: false, arrIndex: null }
  }
})
